apiVersion: v1
kind: Pod
metadata:
  name: pod-comportado
  namespace: treinamento-ch2
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "300Mi"    # Reserva garantida de 300MB
      limits:
        memory: "350Mi"    # Teto máximo de 350MB (250MB + 100MB de margem)