apiVersion: v1
kind: Pod
metadata:
  labels:
    run: waltenne
  name: waltenne
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /waltenne
      name: primeiro-volume
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    args: 
    - sleep
    - "9999"
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /waltenne2
      name: segundo-volume
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: "50Mi"
  - name: segundo-volume
    emptyDir:
      sizeLimit: "100Mi"
status: {}
